language: rust
rust:
  - stable
  - 1.42.0  # lowest rust release against which we guarantee compatibility.
cache: cargo
env:
  - FEATURES='--features chrono'
  - FEATURES=''
before_install:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES
  - cargo clippy --verbose $FEATURES
  - cargo fmt --all -- --check
